console.log("tailwind.config.js loaded");

const colors = require("tailwindcss/colors");

module.exports = {
  future: {},
  purge: [],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      trueGray: colors.trueGray,
      coolGray: colors.coolGray,
      warmGray: colors.warmGray,
      blueGray: colors.blueGray,
      indigo: colors.indigo,
      red: colors.rose,
      yellow: colors.amber,
      green: colors.green,
      orange: colors.orange,
      pink: colors.pink,
      rose: colors.rose,
      fuchsia: colors.fuchsia,
      cyan: colors.cyan,
      teal: colors.teal,
      violet: colors.violet,
      sky: colors.sky,
      emerald: colors.emerald,
      lime: colors.lime,
      amber: colors.amber,
    },
    extend: {
      zIndex: {
        "0": 0,
        "10": 10,
        "20": 20,
        "30": 30,
        "40": 40,
        "50": 50,
        "25": 25,
        "50": 50,
        "75": 75,
        "100": 100,
        "200": 200,
        "300": 300,
        "1000": 1000,
        auto: "auto",
      },
    },
  },
  variants: {},
  plugins: [],
};
